apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: subscriptions-ri
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: argonautcontainerregistry.azurecr.io/subscriptions/client:latest
        env:
        - name: Client_Listen_Url
          value: http://0.0.0.0:56345
        ports:
        - containerPort: 56345
