apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: subscriptions-ri
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      volumes:
      - name: shared-data
        emptyDir: {}
      containers:
      - name: ui
        image: argonautcontainerregistry.azurecr.io/subscriptions/ui:latest
        volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html/env.js
          subPath: env.js
        envFrom:
        - configMapRef:
            name: special-config
        ports:
        - containerPort: 80
      initContainers:
      - name: init-ui-env-to-json
        image: argonautcontainerregistry.azurecr.io/subscriptions/ui:latest
        volumeMounts:
        - name: shared-data
          mountPath: /shared-data
        envFrom:
        - configMapRef:
            name: special-config
        command: ['sh', '-c', 'echo "window._env={\"INSTRUMENTATION_KEY\":\"$INSTRUMENTATION_KEY\", \"Server_Public_Url\":\"$Server_Public_Url\", \"Server_Public_Url_R4\":\"$Server_Public_Url_R4\", \"Server_Public_Url_R5\":\"$Server_Public_Url_R5\", \"Client_Public_Url\":\"$Client_Public_Url\"}" > /shared-data/env.js']
