apiVersion: apps/v1
kind: Deployment
metadata:
  name: ri-ecr
  namespace: subscriptions-ri
  labels:
    app: ri-ecr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ri-ecr
  template:
    metadata:
      labels:
        app: ri-ecr
    spec:
      containers:
      - name: fhir-candle
        image: argonautcontainerregistry.azurecr.io/subscriptions/fhir-candle:latest
        command: ["dotnet"]
        args: ["fhir-candle.dll", "--reference-implementation", "hl7.fhir.us.ecr", "--load-package", "hl7.fhir.us.ecr", "--r4", "r4", "--smart-optional", "r4", "--protect-source", "true", "-m", "1000", "--max-subscription-minutes", "240", "--load-examples", "true"]
        envFrom:
        - configMapRef:
            name: special-config
        env:
        - name: Listen_Port
          value: "5826"
        - name: Public_Url
          value: "https://ecr.ri.argo.run"
        - name: Zulip_Email
          valueFrom:
            secretKeyRef:
              name: argonaut-secrets
              key: Zulip_Email
        - name: Zulip_Key
          valueFrom:
            secretKeyRef:
              name: argonaut-secrets
              key: Zulip_Key
        - name: Zulip_Url
          value: "https://chat.fhir.org"
        - name: SMTP_Host
          valueFrom:
            secretKeyRef:
              name: argonaut-secrets
              key: SMTP_Host
        - name: SMTP_Password
          valueFrom:
            secretKeyRef:
              name: argonaut-secrets
              key: SMTP_Password
        - name: SMTP_Port
          valueFrom:
            secretKeyRef:
              name: argonaut-secrets
              key: SMTP_Port
        - name: SMTP_User
          valueFrom:
            secretKeyRef:
              name: argonaut-secrets
              key: SMTP_User
        ports:
        - containerPort: 5826