apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-proxy
  namespace: subscriptions-ri
  labels:
    app: server-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server-proxy
  template:
    metadata:
      labels:
        app: server-proxy
    spec:
      containers:
      - name: server-proxy
        image: argonautcontainerregistry.azurecr.io/subscriptions/server-proxy:latest
        envFrom:
        - configMapRef:
            name: special-config
        env:
        - name: Sendpulse_User_Id
          valueFrom:
            secretKeyRef:
              name: argonaut-secrets
              key: Sendpulse_User_Id
        - name: Sendpulse_Secret
          valueFrom:
            secretKeyRef:
              name: argonaut-secrets
              key: Sendpulse_Secret
        - name: Sendpulse_Sender
          valueFrom:
            secretKeyRef:
              name: argonaut-secrets
              key: Sendpulse_Sender
        - name: Zulip_Email
          valueFrom:
            secretKeyRef:
              name: argonaut-secrets
              key: Zulip_Email
        - name: Zulip_Key
          valueFrom:
            secretKeyRef:
              name: argonaut-secrets
              key: Zulip_Key
        - name: Zulip_Site
          value: "https://chat.fhir.org"
        ports:
        - containerPort: 56340