kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: subscriptions-ingress
  namespace: subscriptions-ri
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
spec:
  tls:
  - hosts:
    - subscriptions.argo.run
    - pas.ri.argo.run
    - vitals-server.ri.argo.run
    secretName: tls-secret
  rules:
  - host: subscriptions.argo.run
    http:
      paths:
      - backend:
          service:
            name: ri-subscriptions
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: pas.ri.argo.run
    http:
      paths:
      - backend:
          service:
            name: ri-pas
            port:
              number: 80
        path: /
        pathType: Prefix
  - host: vitals-server.ri.argo.run
    http:
      paths:
      - backend:
          service:
            name: ri-vitals-server
            port:
              number: 80
        path: /
        pathType: Prefix
